#!/usr/bin/python2 -BOO
# PDBF - Python DBF Implementation
#################################################################################
# This program is free software: you can redistribute it and/or modify		#
# it under the terms of the GNU General Public License as published by		#
# the Free Software Foundation, either version 3 of the License, or		#
# (at your option) any later version.						#
#										#
# This program is distributed in the hope that it will be useful,		#
# but WITHOUT ANY WARRANTY; without even the implied warranty of		#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the			#
# GNU General Public License for more details.					#
#										#
# You should have received a copy of the GNU General Public License		#
# along with this program.  If not, see <http://www.gnu.org/licenses/>.		#
#################################################################################
import sys
memory = []
for i in range(0,65536):
	memory.append(0)
try:
	filename = sys.argv[1]
except:
	print "Usage: pdbi [file]"
	sys.exit(1)
datapointer = 0
commands = []
current_command = 0
infile = open(filename,'r').read().replace("\t","").replace("\n","").replace(" ","")
for j in range(0,len(infile)):
	if j%2==1:
		commands.append(infile[j-1]+str(infile[j]))
while True:
	x = commands[current_command]
	if x == 'FF':
		datapointer += 1
	elif x == 'BB':
		datapointer -= 1
	elif x == 'II':
		memory[datapointer] += 1
	elif x == 'DD':
		memory[datapointer] -= 1
	elif x == 'OO':
		sys.stdout.write(chr(memory[datapointer]))
		sys.stdout.flush()
	elif x.startswith('J'):
		command += int(x[1])
	else:
		pass
	current_command += 1
	if current_command >= len(commands):
		break
